In [1]:
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow import keras

WARNING:tensorflow:From C:\Users\vansh\AppData\Roaming\Python\Python310\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
df = pd.read_csv('hand_gestures.csv')
df.head()

,label,x0,y0,x1,y1,x2,y2,x3,y3,x4,...,x16,y16,x17,y17,x18,y18,x19,y19,x20,y20
0,forward,379.614639,449.260540,321.944313,438.132362,273.655663,397.948208,236.639080,364.140358,201.107445,...,380.280304,157.375531,413.422546,316.954679,425.114365,268.114929,433.474426,236.828499,439.722443,207.345772
1,forward,259.853134,410.937080,199.420433,391.884499,151.260071,341.330566,117.858086,297.937975,81.299133,...,273.248425,86.419916,296.788597,274.616632,312.098007,219.955530,324.150085,179.874644,335.274963,141.984973
2,forward,465.596848,385.507565,402.487183,369.328251,348.662682,323.471889,310.492668,282.177801,272.951756,...,471.037369,59.457879,506.413994,237.273273,521.501923,183.335338,531.450500,146.527433,538.472137,112.058566
3,forward,486.378098,424.512863,425.585289,404.690723,377.506065,357.511082,357.815170,306.893492,378.663177,...,464.959221,103.359618,518.896370,273.252010,515.311012,218.633223,512.555008,182.348886,508.559723,147.821002
4,forward,414.147034,352.346334,343.611832,321.030636,301.921120,268.856821,277.962685,221.220975,248.057060,...,312.605476,70.909324,379.719124,192.420774,364.628372,149.038754,354.786987,123.230009,347.112122,97.440605

In [3]:
df['label'].value_counts()

left        1320
right       1320
backward    1210
up           880
down         880
flip         880
land         880
forward      770
Name: label, dtype: int64

In [4]:
df['label'] = df['label'].map({'forward': 0, 'backward': 1, 'up': 2, 'down': 3, 'left': 4, 'right': 5, 'flip': 6, 'land': 7})

In [5]:
input = tf.constant(df)
tensor_data = tf.random.shuffle(input)

In [6]:
x_train = tensor_data[:int(len(tensor_data)*0.9), 1:]
y_train = tensor_data[:int(len(tensor_data)*0.9), :1]

x_test = tensor_data[int(len(tensor_data)*0.9):, 1:]
y_test = tensor_data[int(len(tensor_data)*0.9):, :1]

In [10]:
x_train.shape

TensorShape([7326, 42])

In [17]:
x_test.shape

TensorShape([814, 42])

In [16]:
a = pd.DataFrame(x_train)
b = pd.DataFrame(x_test)
pd.concat([a,b])

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,251.548824,8.127661,295.342140,32.316537,318.536835,79.142685,320.973549,123.540211,315.567856,156.281214,...,263.278160,111.677723,260.579128,84.730949,242.737560,130.382261,239.662361,113.701982,244.892101,96.580262
1,317.294807,377.683897,258.827515,340.936947,214.120789,288.161287,192.947121,235.082617,212.786713,202.426071,...,332.907143,217.620192,379.979706,250.602665,376.883774,164.976325,374.631195,124.012184,375.191193,93.521333
2,515.751038,404.183254,481.403809,396.433601,443.093376,374.448900,437.955170,346.595497,469.108696,327.627087,...,529.397469,358.315420,566.620865,316.952925,553.511887,323.906984,550.465622,359.079885,554.991760,356.745205
3,102.526045,339.798260,161.052628,322.670574,207.202206,273.776436,222.819519,229.648762,201.080627,219.045811,...,133.334198,23.317208,72.628307,190.317049,78.207502,135.814648,85.326910,101.708379,95.093231,69.795098
4,448.552666,31.038623,402.978249,79.596376,390.009537,141.031651,408.709030,186.215873,440.287704,204.632564,...,472.499580,163.328118,527.484703,135.500779,506.412354,171.263509,495.070992,157.336793,494.945412,142.284021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,466.205521,395.149641,427.070045,389.014492,372.859039,355.631933,354.628220,314.530592,379.821739,281.180849,...,453.080673,320.663109,489.853935,253.546200,480.408478,276.151886,483.336258,316.456633,485.760651,311.787071
810,430.516357,313.734207,362.769966,269.356766,328.108253,226.733646,309.718246,187.838154,306.633072,155.559893,...,369.217262,201.411948,417.176514,159.355440,351.612587,164.944334,358.265152,197.543058,383.991928,203.003292
811,412.136307,376.121807,357.566872,365.566435,304.765930,328.306017,267.610111,303.234243,233.022041,295.704918,...,384.458427,298.309937,427.411385,238.872943,423.465347,191.533699,424.898529,167.327900,430.015717,145.202329
812,345.737610,334.725437,402.867889,334.319544,461.953125,298.758059,508.565331,272.938471,551.937027,260.161171,...,372.778168,285.025749,328.838730,212.558298,326.743431,157.793784,325.214825,125.306182,327.088165,89.929390
813,308.443947,471.348124,252.688293,434.771633,231.851311,377.340174,254.391098,326.840944,286.977596,306.540928,...,321.885796,335.969610,381.652718,376.063442,358.518181,320.349054,344.511719,332.890406,345.850639,352.328253

In [51]:
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    # keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(8, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss = 'sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=100, callbacks=keras.callbacks.EarlyStopping(monitor='accuracy', patience=5))

Epoch 1/100

229/229 [==============================] - 2s 3ms/step - loss: 1.7661 - accuracy: 0.7824
Epoch 2/100
229/229 [==============================] - 1s 3ms/step - loss: 0.1112 - accuracy: 0.9645
Epoch 3/100
229/229 [==============================] - 1s 3ms/step - loss: 0.0245 - accuracy: 0.9932
Epoch 4/100
229/229 [==============================] - 1s 3ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 5/100
229/229 [==============================] - 1s 3ms/step - loss: 0.0010 - accuracy: 1.0000
Epoch 6/100
229/229 [==============================] - 1s 3ms/step - loss: 5.0303e-04 - accuracy: 1.0000
Epoch 7/100
229/229 [==============================] - 1s 3ms/step - loss: 3.9627e-04 - accuracy: 1.0000
Epoch 8/100
229/229 [==============================] - 1s 3ms/step - loss: 3.1678e-04 - accuracy: 1.0000
Epoch 9/100
229/229 [==============================] - 1s 3ms/step - loss: 1.8044e-04 - accuracy: 1.0000

In [54]:
model.evaluate(x_test, y_test)

26/26 [==============================] - 0s 3ms/step - loss: 1.6026e-04 - accuracy: 1.0000

[0.00016025530931074172, 1.0]

In [52]:
print(blabla)

NameError: name 'blabla' is not defined

In [56]:
model.save('landmark-model.keras')